In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df_base = pd.read_csv("raw_dataset_from_scrapping.csv")

display(df_base)

df_base.info()

,Unnamed: 0,Título,Reais,Centavos,Condição,Nota,N_Avaliações,Desconto,Marca,Material,Gênero,Temporada,Review1,Review2,Review3
0,0,Pijama Cirurgico Scrub Roupa Privativa Hospit...,69.0,90.0,Novo | +1000 vendidos,4.0,(273),NaN,TORONTO UNIFORMES PROFISSIONAIS,Poliéster,Sem gênero,NaN,"Preço justo , bem feito acabamento ok. Única s...","Tamanho bom, costuras de qualidade, porém teci...","Muito bom, só poderia ter os cortes na lateral..."
1,1,Kit 10 Cuecas Boxer Lupo Cueca Box Algodão Mas...,232.0,89.0,Novo | +10mil vendidos,4.5,(3034),18% OFF,Lupo,Algodão,Masculino,Outono/Inverno,As cuecas são boas; porém você percebe na cost...,"Pelo preço promocional, com ctz tem algum defe...","Serviram muito bem, porém é nítido que o pano ..."
2,2,Kit Com 10 Cuecas Boxer Algodão Sem Costura Zo...,199.0,90.0,Novo | +50mil vendidos,4.7,(5682),20% OFF,Zorba,Algodão,Masculino,NaN,O tecido é bom e são confortáveis. Só que a nu...,Vendo comentários de outros consumidores vejo ...,"Produto não é nem de longe original, tecido gr..."
3,3,Kit 10 Cuecas Boxer Mash Algodão Cotton Box Or...,229.0,39.0,Novo | +10mil vendidos,4.6,(1700),22% OFF,Mash,Algodão,Masculino,Primavera/Verão,"As cuecas são boas, porém meu marido usa g e p...","E o tamanho certo, mas em baixo dela, fica mui...",Produto não parece.\nOriginal e veio 2 modelos...
4,4,Kit 3 Short Jeans Feminino Cintura Alta Barato...,129.0,20.0,Novo | +1000 vendidos,4.4,(507),9% OFF,Menina Linda,Jean,Feminino,Primavera/Verão,Estou encantada com essas peças!.\nOs shorts s...,"Recomendo, tecido confortável, igual a foto.","Gostei muito dos shorts, material bom, para us..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202,2202,Bermuda Masculina Tática Thunder Poly Ripstop ...,119.0,80.0,Novo | +5 vendidos,4.3,(3),10% OFF,Use Tático,Poliéster,Masculino,Primavera/Verão,Muito bom produto gostei muito.,Tá ótimo recomendo a todos.,NaN
2203,2203,Camiseta Preta Juvenil Infantil Menina Menino ...,20.0,5.0,Novo | +25 vendidos,NaN,NaN,13% OFF,DestaQ,Algodão,Sem gênero infantil,NaN,NaN,NaN,NaN
2204,2204,Blusa Personalizada Jaqueta Com Sua Marca Logo...,93.0,99.0,Novo | 1 vendido,NaN,NaN,NaN,Inoffensive,NaN,Feminino,NaN,NaN,NaN,NaN
2205,2205,Roupa Infantil Social Menino - Bebê Batizado F...,97.0,3.0,Novo | +50 vendidos,4.7,(14),NaN,Balão Magico Kids,NaN,Bebês,NaN,"O roupa em si é linda, só a camisa que o tecid...",Amei.,Ficou perfeito no meu filho.
2206,2206,Kit -06 Shortinhos Micro Colado Para Usar Com ...,103.0,87.0,Novo | +5 vendidos,NaN,NaN,NaN,Madasi,Viscolycra,Feminino,Primavera/Verão,NaN,NaN,NaN

<class 'pandas.DataFrame'>
RangeIndex: 2207 entries, 0 to 2206
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    2207 non-null   int64
 1   Título        2207 non-null   str
 2   Reais         2207 non-null   float64
 3   Centavos      1964 non-null   float64
 4   Condição      2207 non-null   str
 5   Nota          1559 non-null   float64
 6   N_Avaliações  1559 non-null   str
 7   Desconto      874 non-null    str
 8   Marca         2184 non-null   str
 9   Material      1332 non-null   str
 10  Gênero        2120 non-null   str
 11  Temporada     1135 non-null   str
 12  Review1       1515 non-null   str
 13  Review2       1354 non-null   str
 14  Review3       1233 non-null   str
dtypes: float64(3), int64(1), str(11)
memory usage: 258.8 KB

In [47]:
# Tratamento da tabela

# Renomeando coluna
df_analise = df_base.rename(columns={"Unnamed: 0": "Id"})

# Adicionando nova coluna
df_analise["Preço"] = df_analise["Reais"] + (df_analise["Centavos"]/100)

#Mudando de posição a coluna da tabela
coluna = df_analise.pop("Preço")
df_analise.insert(2,"Preço",coluna)
df_analise = df_analise.drop(columns=["Reais","Centavos"])

# Removendo caracteres indesejaveis da coluna N_Avaliações

df_analise["N_Avaliações"] = (
    df_analise["N_Avaliações"]
    .str.replace("(","")
    .str.replace(")","")
 )

# Tratando valores nulos e dataType 
df_analise["N_Avaliações"].value_counts()

df_analise["N_Avaliações"] = df_analise["N_Avaliações"].fillna(0)

df_analise["N_Avaliações"] = df_analise["N_Avaliações"].astype("int64")


# Tirando caracteres indesejaveis da coluna
df_analise["Desconto"].value_counts()

df_analise["Desconto"] = (
    df_analise["Desconto"]
    .str.replace("%","")
    .str.replace(" ", "")
    .str.replace("OFF","")
 )

# Mudando dataType, tratando valores nulos e tratando valores inteiro para decimal
df_analise["Desconto"] = df_analise["Desconto"].astype("float64")

df_analise["Desconto"] = df_analise["Desconto"] / 100

df_analise["Desconto"] = df_analise["Desconto"].fillna(0.0)

# Trazendo o valor original do produto
valor_desconto = df_analise["Preço"] * df_analise["Desconto"]

df_analise["Preço"] = (df_analise["Preço"] + valor_desconto).round(2)

# Criação de nova coluna
df_analise["Preco_com_desconto"] = (df_analise["Preço"] * (1 - df_analise["Desconto"])).round(2)

# Ordenando posições das colunas na tabela novamente
coluna2 = df_analise.pop("Desconto")
df_analise.insert(3,"Desconto",coluna2)

coluna3 = df_analise.pop("Preco_com_desconto")
df_analise.insert(4,"Preco_com_desconto",coluna3)

display(df_analise)

df_analise.info()

,Id,Título,Preço,Desconto,Preco_com_desconto,Condição,Nota,N_Avaliações,Marca,Material,Gênero,Temporada,Review1,Review2,Review3
0,0,Pijama Cirurgico Scrub Roupa Privativa Hospit...,69.90,0.00,69.90,Novo | +1000 vendidos,4.0,273,TORONTO UNIFORMES PROFISSIONAIS,Poliéster,Sem gênero,NaN,"Preço justo , bem feito acabamento ok. Única s...","Tamanho bom, costuras de qualidade, porém teci...","Muito bom, só poderia ter os cortes na lateral..."
1,1,Kit 10 Cuecas Boxer Lupo Cueca Box Algodão Mas...,274.81,0.18,225.34,Novo | +10mil vendidos,4.5,3034,Lupo,Algodão,Masculino,Outono/Inverno,As cuecas são boas; porém você percebe na cost...,"Pelo preço promocional, com ctz tem algum defe...","Serviram muito bem, porém é nítido que o pano ..."
2,2,Kit Com 10 Cuecas Boxer Algodão Sem Costura Zo...,239.88,0.20,191.90,Novo | +50mil vendidos,4.7,5682,Zorba,Algodão,Masculino,NaN,O tecido é bom e são confortáveis. Só que a nu...,Vendo comentários de outros consumidores vejo ...,"Produto não é nem de longe original, tecido gr..."
3,3,Kit 10 Cuecas Boxer Mash Algodão Cotton Box Or...,279.86,0.22,218.29,Novo | +10mil vendidos,4.6,1700,Mash,Algodão,Masculino,Primavera/Verão,"As cuecas são boas, porém meu marido usa g e p...","E o tamanho certo, mas em baixo dela, fica mui...",Produto não parece.\nOriginal e veio 2 modelos...
4,4,Kit 3 Short Jeans Feminino Cintura Alta Barato...,140.83,0.09,128.16,Novo | +1000 vendidos,4.4,507,Menina Linda,Jean,Feminino,Primavera/Verão,Estou encantada com essas peças!.\nOs shorts s...,"Recomendo, tecido confortável, igual a foto.","Gostei muito dos shorts, material bom, para us..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202,2202,Bermuda Masculina Tática Thunder Poly Ripstop ...,131.78,0.10,118.60,Novo | +5 vendidos,4.3,3,Use Tático,Poliéster,Masculino,Primavera/Verão,Muito bom produto gostei muito.,Tá ótimo recomendo a todos.,NaN
2203,2203,Camiseta Preta Juvenil Infantil Menina Menino ...,22.66,0.13,19.71,Novo | +25 vendidos,NaN,0,DestaQ,Algodão,Sem gênero infantil,NaN,NaN,NaN,NaN
2204,2204,Blusa Personalizada Jaqueta Com Sua Marca Logo...,93.99,0.00,93.99,Novo | 1 vendido,NaN,0,Inoffensive,NaN,Feminino,NaN,NaN,NaN,NaN
2205,2205,Roupa Infantil Social Menino - Bebê Batizado F...,97.03,0.00,97.03,Novo | +50 vendidos,4.7,14,Balão Magico Kids,NaN,Bebês,NaN,"O roupa em si é linda, só a camisa que o tecid...",Amei.,Ficou perfeito no meu filho.
2206,2206,Kit -06 Shortinhos Micro Colado Para Usar Com ...,103.87,0.00,103.87,Novo | +5 vendidos,NaN,0,Madasi,Viscolycra,Feminino,Primavera/Verão,NaN,NaN,NaN

<class 'pandas.DataFrame'>
RangeIndex: 2207 entries, 0 to 2206
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id                  2207 non-null   int64
 1   Título              2207 non-null   str
 2   Preço               1964 non-null   float64
 3   Desconto            2207 non-null   float64
 4   Preco_com_desconto  1964 non-null   float64
 5   Condição            2207 non-null   str
 6   Nota                1559 non-null   float64
 7   N_Avaliações        2207 non-null   int64
 8   Marca               2184 non-null   str
 9   Material            1332 non-null   str
 10  Gênero              2120 non-null   str
 11  Temporada           1135 non-null   str
 12  Review1             1515 non-null   str
 13  Review2             1354 non-null   str
 14  Review3             1233 non-null   str
dtypes: float64(4), int64(2), str(9)
memory usage: 258.8 KB

In [48]:
# Continuação do Tratamento da tabela

# Tabelas com nulos indevidamente : marca, material, genero, temporada

df_analise["Marca"] = df_analise["Marca"].fillna("Desconhecida")

df_analise["Material"] = df_analise["Material"].fillna("Não Informado")

df_analise["Temporada"] = df_analise["Temporada"].fillna("Não Informado")

df_analise["Gênero"] = df_analise["Gênero"].fillna("Não Informado")
df_analise.info()

<class 'pandas.DataFrame'>
RangeIndex: 2207 entries, 0 to 2206
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id                  2207 non-null   int64
 1   Título              2207 non-null   str
 2   Preço               1964 non-null   float64
 3   Desconto            2207 non-null   float64
 4   Preco_com_desconto  1964 non-null   float64
 5   Condição            2207 non-null   str
 6   Nota                1559 non-null   float64
 7   N_Avaliações        2207 non-null   int64
 8   Marca               2207 non-null   str
 9   Material            2207 non-null   str
 10  Gênero              2207 non-null   str
 11  Temporada           2207 non-null   str
 12  Review1             1515 non-null   str
 13  Review2             1354 non-null   str
 14  Review3             1233 non-null   str
dtypes: float64(4), int64(2), str(9)
memory usage: 258.8 KB

In [49]:
# Analises 

#Produtos com maior preço
df_analise.sort_values(by="Preço",ascending=False)

# Produtos com desconto maior que 30%
df_analise[df_analise["Desconto"] > 0.30]

#Produtos sem avaliação
df_analise[df_analise["N_Avaliações"] == 0]

#Quantidade de produtos por genero
df_analise["Gênero"].value_counts()

Gênero
Feminino                             723
Masculino                            545
Bebês                                311
Sem gênero                           248
Meninas                              119
Meninos                              108
Não Informado                         87
Sem gênero infantil                   54
Mulher                                 4
short menina verao look mulher         3
roupa para gordinha pluss P ao 52      2
Unissex                                1
menino                                 1
bermuda feminina brilho Blogueira      1
Name: count, dtype: int64

In [61]:
# Criação de tabela Estatisticas
estatisticas = pd.DataFrame({
        "Estatisticas":["Média","Mediana","Moda","Desvio_Padrão","Valor_maximo","valor_minimo","Amplitude","skew","Kurtosis"],
        "Valor": [
            df_analise["Preço"].mean(),
            df_analise["Preço"].median(),
            df_analise["Preço"].mode()[0],
            df_analise["Preço"].std(),
            df_analise["Preço"].max(),
            df_analise["Preço"].min(),
            df_analise["Preço"].max() -  df_analise["Preço"].min(),
            df_analise["Preço"].skew(),
            df_analise["Preço"].kurt()

        ]
}).round(2).T
display(estatisticas)

,0,1,2,3,4,5,6,7,8
Estatisticas,Média,Mediana,Moda,Desvio_Padrão,Valor_maximo,valor_minimo,Amplitude,skew,Kurtosis
Valor,110.44,86.5,78.9,76.98,657.03,10.88,646.15,1.82,5.49